/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// 置群成员专属头衔
    /// </summary>
    [DataContract]
    public partial class CqpCQSetGroupSpecialTitleHttpInput :  IEquatable<CqpCQSetGroupSpecialTitleHttpInput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CqpCQSetGroupSpecialTitleHttpInput" /> class.
        /// </summary>
        /// <param name="群号">目标群.</param>
        /// <param name="qqid">目标QQ.</param>
        /// <param name="头衔">如果要删除，这里填空.</param>
        /// <param name="过期时间">专属头衔有效期，单位为秒。如果永久有效，这里填写-1.</param>
        public CqpCQSetGroupSpecialTitleHttpInput(long? 群号 = default(long?), long? qqid = default(long?), string 头衔 = default(string), long? 过期时间 = default(long?))
        {
            this.群号 = 群号;
            this.Qqid = qqid;
            this.头衔 = 头衔;
            this.过期时间 = 过期时间;
        }
        
        /// <summary>
        /// 目标群
        /// </summary>
        /// <value>目标群</value>
        [DataMember(Name="群号", EmitDefaultValue=false)]
        public long? 群号 { get; set; }

        /// <summary>
        /// 目标QQ
        /// </summary>
        /// <value>目标QQ</value>
        [DataMember(Name="qqid", EmitDefaultValue=false)]
        public long? Qqid { get; set; }

        /// <summary>
        /// 如果要删除，这里填空
        /// </summary>
        /// <value>如果要删除，这里填空</value>
        [DataMember(Name="头衔", EmitDefaultValue=false)]
        public string 头衔 { get; set; }

        /// <summary>
        /// 专属头衔有效期，单位为秒。如果永久有效，这里填写-1
        /// </summary>
        /// <value>专属头衔有效期，单位为秒。如果永久有效，这里填写-1</value>
        [DataMember(Name="过期时间", EmitDefaultValue=false)]
        public long? 过期时间 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CqpCQSetGroupSpecialTitleHttpInput {\n");
            sb.Append("  群号: ").Append(群号).Append("\n");
            sb.Append("  Qqid: ").Append(Qqid).Append("\n");
            sb.Append("  头衔: ").Append(头衔).Append("\n");
            sb.Append("  过期时间: ").Append(过期时间).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CqpCQSetGroupSpecialTitleHttpInput);
        }

        /// <summary>
        /// Returns true if CqpCQSetGroupSpecialTitleHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of CqpCQSetGroupSpecialTitleHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CqpCQSetGroupSpecialTitleHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.群号 == input.群号 ||
                    (this.群号 != null &&
                    this.群号.Equals(input.群号))
                ) && 
                (
                    this.Qqid == input.Qqid ||
                    (this.Qqid != null &&
                    this.Qqid.Equals(input.Qqid))
                ) && 
                (
                    this.头衔 == input.头衔 ||
                    (this.头衔 != null &&
                    this.头衔.Equals(input.头衔))
                ) && 
                (
                    this.过期时间 == input.过期时间 ||
                    (this.过期时间 != null &&
                    this.过期时间.Equals(input.过期时间))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.群号 != null)
                    hashCode = hashCode * 59 + this.群号.GetHashCode();
                if (this.Qqid != null)
                    hashCode = hashCode * 59 + this.Qqid.GetHashCode();
                if (this.头衔 != null)
                    hashCode = hashCode * 59 + this.头衔.GetHashCode();
                if (this.过期时间 != null)
                    hashCode = hashCode * 59 + this.过期时间.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
