/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// &#x60;
    /// </summary>
    [DataContract]
    public partial class MpqApiSendObjectMsgHttpInput :  IEquatable<MpqApiSendObjectMsgHttpInput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MpqApiSendObjectMsgHttpInput" /> class.
        /// </summary>
        /// <param name="响应的QQ">响应的QQ.</param>
        /// <param name="收信对象类型">同Api_SendMsg  1好友 2群 3讨论组 4群临时会话 5讨论组临时会话.</param>
        /// <param name="收信对象所属群讨论组">发群内、临时会话必填 好友可不填.</param>
        /// <param name="收信对象QQ">临时会话、好友必填 发至群内可不填.</param>
        /// <param name="objectMsg">objectMsg.</param>
        /// <param name="结构子类型">00 基本 02 点歌 其他不明.</param>
        public MpqApiSendObjectMsgHttpInput(string 响应的QQ = default(string), int? 收信对象类型 = default(int?), string 收信对象所属群讨论组 = default(string), string 收信对象QQ = default(string), string objectMsg = default(string), int? 结构子类型 = default(int?))
        {
            this.响应的QQ = 响应的QQ;
            this.收信对象类型 = 收信对象类型;
            this.收信对象所属群讨论组 = 收信对象所属群讨论组;
            this.收信对象QQ = 收信对象QQ;
            this.ObjectMsg = objectMsg;
            this.结构子类型 = 结构子类型;
        }
        
        /// <summary>
        /// Gets or Sets 响应的QQ
        /// </summary>
        [DataMember(Name="响应的QQ", EmitDefaultValue=false)]
        public string 响应的QQ { get; set; }

        /// <summary>
        /// 同Api_SendMsg  1好友 2群 3讨论组 4群临时会话 5讨论组临时会话
        /// </summary>
        /// <value>同Api_SendMsg  1好友 2群 3讨论组 4群临时会话 5讨论组临时会话</value>
        [DataMember(Name="收信对象类型", EmitDefaultValue=false)]
        public int? 收信对象类型 { get; set; }

        /// <summary>
        /// 发群内、临时会话必填 好友可不填
        /// </summary>
        /// <value>发群内、临时会话必填 好友可不填</value>
        [DataMember(Name="收信对象所属群_讨论组", EmitDefaultValue=false)]
        public string 收信对象所属群讨论组 { get; set; }

        /// <summary>
        /// 临时会话、好友必填 发至群内可不填
        /// </summary>
        /// <value>临时会话、好友必填 发至群内可不填</value>
        [DataMember(Name="收信对象QQ", EmitDefaultValue=false)]
        public string 收信对象QQ { get; set; }

        /// <summary>
        /// Gets or Sets ObjectMsg
        /// </summary>
        [DataMember(Name="objectMsg", EmitDefaultValue=false)]
        public string ObjectMsg { get; set; }

        /// <summary>
        /// 00 基本 02 点歌 其他不明
        /// </summary>
        /// <value>00 基本 02 点歌 其他不明</value>
        [DataMember(Name="结构子类型", EmitDefaultValue=false)]
        public int? 结构子类型 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MpqApiSendObjectMsgHttpInput {\n");
            sb.Append("  响应的QQ: ").Append(响应的QQ).Append("\n");
            sb.Append("  收信对象类型: ").Append(收信对象类型).Append("\n");
            sb.Append("  收信对象所属群讨论组: ").Append(收信对象所属群讨论组).Append("\n");
            sb.Append("  收信对象QQ: ").Append(收信对象QQ).Append("\n");
            sb.Append("  ObjectMsg: ").Append(ObjectMsg).Append("\n");
            sb.Append("  结构子类型: ").Append(结构子类型).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MpqApiSendObjectMsgHttpInput);
        }

        /// <summary>
        /// Returns true if MpqApiSendObjectMsgHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of MpqApiSendObjectMsgHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MpqApiSendObjectMsgHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.响应的QQ == input.响应的QQ ||
                    (this.响应的QQ != null &&
                    this.响应的QQ.Equals(input.响应的QQ))
                ) && 
                (
                    this.收信对象类型 == input.收信对象类型 ||
                    (this.收信对象类型 != null &&
                    this.收信对象类型.Equals(input.收信对象类型))
                ) && 
                (
                    this.收信对象所属群讨论组 == input.收信对象所属群讨论组 ||
                    (this.收信对象所属群讨论组 != null &&
                    this.收信对象所属群讨论组.Equals(input.收信对象所属群讨论组))
                ) && 
                (
                    this.收信对象QQ == input.收信对象QQ ||
                    (this.收信对象QQ != null &&
                    this.收信对象QQ.Equals(input.收信对象QQ))
                ) && 
                (
                    this.ObjectMsg == input.ObjectMsg ||
                    (this.ObjectMsg != null &&
                    this.ObjectMsg.Equals(input.ObjectMsg))
                ) && 
                (
                    this.结构子类型 == input.结构子类型 ||
                    (this.结构子类型 != null &&
                    this.结构子类型.Equals(input.结构子类型))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.响应的QQ != null)
                    hashCode = hashCode * 59 + this.响应的QQ.GetHashCode();
                if (this.收信对象类型 != null)
                    hashCode = hashCode * 59 + this.收信对象类型.GetHashCode();
                if (this.收信对象所属群讨论组 != null)
                    hashCode = hashCode * 59 + this.收信对象所属群讨论组.GetHashCode();
                if (this.收信对象QQ != null)
                    hashCode = hashCode * 59 + this.收信对象QQ.GetHashCode();
                if (this.ObjectMsg != null)
                    hashCode = hashCode * 59 + this.ObjectMsg.GetHashCode();
                if (this.结构子类型 != null)
                    hashCode = hashCode * 59 + this.结构子类型.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
