/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// 向对象、目标发送信息 支持好友 群 讨论组 群临时会话 讨论组临时会话&#x60;
    /// </summary>
    [DataContract]
    public partial class MpqApiSendMsgHttpInput :  IEquatable<MpqApiSendMsgHttpInput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MpqApiSendMsgHttpInput" /> class.
        /// </summary>
        /// <param name="响应的QQ">响应的QQ.</param>
        /// <param name="信息类型">1好友 2群 3讨论组 4群临时会话 5讨论组临时会话.</param>
        /// <param name="参考子类型">无特殊说明情况下留空或填零.</param>
        /// <param name="收信群讨论组">发送群信息、讨论组信息、群临时会话信息、讨论组临时会话信息时填写.</param>
        /// <param name="收信对象">最终接收这条信息的对象QQ.</param>
        /// <param name="内容">信息内容.</param>
        public MpqApiSendMsgHttpInput(string 响应的QQ = default(string), int? 信息类型 = default(int?), int? 参考子类型 = default(int?), string 收信群讨论组 = default(string), string 收信对象 = default(string), string 内容 = default(string))
        {
            this.响应的QQ = 响应的QQ;
            this.信息类型 = 信息类型;
            this.参考子类型 = 参考子类型;
            this.收信群讨论组 = 收信群讨论组;
            this.收信对象 = 收信对象;
            this.内容 = 内容;
        }
        
        /// <summary>
        /// Gets or Sets 响应的QQ
        /// </summary>
        [DataMember(Name="响应的QQ", EmitDefaultValue=false)]
        public string 响应的QQ { get; set; }

        /// <summary>
        /// 1好友 2群 3讨论组 4群临时会话 5讨论组临时会话
        /// </summary>
        /// <value>1好友 2群 3讨论组 4群临时会话 5讨论组临时会话</value>
        [DataMember(Name="信息类型", EmitDefaultValue=false)]
        public int? 信息类型 { get; set; }

        /// <summary>
        /// 无特殊说明情况下留空或填零
        /// </summary>
        /// <value>无特殊说明情况下留空或填零</value>
        [DataMember(Name="参考子类型", EmitDefaultValue=false)]
        public int? 参考子类型 { get; set; }

        /// <summary>
        /// 发送群信息、讨论组信息、群临时会话信息、讨论组临时会话信息时填写
        /// </summary>
        /// <value>发送群信息、讨论组信息、群临时会话信息、讨论组临时会话信息时填写</value>
        [DataMember(Name="收信群_讨论组", EmitDefaultValue=false)]
        public string 收信群讨论组 { get; set; }

        /// <summary>
        /// 最终接收这条信息的对象QQ
        /// </summary>
        /// <value>最终接收这条信息的对象QQ</value>
        [DataMember(Name="收信对象", EmitDefaultValue=false)]
        public string 收信对象 { get; set; }

        /// <summary>
        /// 信息内容
        /// </summary>
        /// <value>信息内容</value>
        [DataMember(Name="内容", EmitDefaultValue=false)]
        public string 内容 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MpqApiSendMsgHttpInput {\n");
            sb.Append("  响应的QQ: ").Append(响应的QQ).Append("\n");
            sb.Append("  信息类型: ").Append(信息类型).Append("\n");
            sb.Append("  参考子类型: ").Append(参考子类型).Append("\n");
            sb.Append("  收信群讨论组: ").Append(收信群讨论组).Append("\n");
            sb.Append("  收信对象: ").Append(收信对象).Append("\n");
            sb.Append("  内容: ").Append(内容).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MpqApiSendMsgHttpInput);
        }

        /// <summary>
        /// Returns true if MpqApiSendMsgHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of MpqApiSendMsgHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MpqApiSendMsgHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.响应的QQ == input.响应的QQ ||
                    (this.响应的QQ != null &&
                    this.响应的QQ.Equals(input.响应的QQ))
                ) && 
                (
                    this.信息类型 == input.信息类型 ||
                    (this.信息类型 != null &&
                    this.信息类型.Equals(input.信息类型))
                ) && 
                (
                    this.参考子类型 == input.参考子类型 ||
                    (this.参考子类型 != null &&
                    this.参考子类型.Equals(input.参考子类型))
                ) && 
                (
                    this.收信群讨论组 == input.收信群讨论组 ||
                    (this.收信群讨论组 != null &&
                    this.收信群讨论组.Equals(input.收信群讨论组))
                ) && 
                (
                    this.收信对象 == input.收信对象 ||
                    (this.收信对象 != null &&
                    this.收信对象.Equals(input.收信对象))
                ) && 
                (
                    this.内容 == input.内容 ||
                    (this.内容 != null &&
                    this.内容.Equals(input.内容))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.响应的QQ != null)
                    hashCode = hashCode * 59 + this.响应的QQ.GetHashCode();
                if (this.信息类型 != null)
                    hashCode = hashCode * 59 + this.信息类型.GetHashCode();
                if (this.参考子类型 != null)
                    hashCode = hashCode * 59 + this.参考子类型.GetHashCode();
                if (this.收信群讨论组 != null)
                    hashCode = hashCode * 59 + this.收信群讨论组.GetHashCode();
                if (this.收信对象 != null)
                    hashCode = hashCode * 59 + this.收信对象.GetHashCode();
                if (this.内容 != null)
                    hashCode = hashCode * 59 + this.内容.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
