/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// 设置在线状态+附加信息 &#x60;
    /// </summary>
    [DataContract]
    public partial class MpqApiSetOLStatusHttpInput :  IEquatable<MpqApiSetOLStatusHttpInput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MpqApiSetOLStatusHttpInput" /> class.
        /// </summary>
        /// <param name="响应的QQ">响应的QQ.</param>
        /// <param name="在线状态">1~6 分别对应我在线上, Q我吧, 离开, 忙碌, 请勿打扰, 隐身.</param>
        /// <param name="状态附加信息">最大255字节.</param>
        public MpqApiSetOLStatusHttpInput(string 响应的QQ = default(string), int? 在线状态 = default(int?), string 状态附加信息 = default(string))
        {
            this.响应的QQ = 响应的QQ;
            this.在线状态 = 在线状态;
            this.状态附加信息 = 状态附加信息;
        }
        
        /// <summary>
        /// Gets or Sets 响应的QQ
        /// </summary>
        [DataMember(Name="响应的QQ", EmitDefaultValue=false)]
        public string 响应的QQ { get; set; }

        /// <summary>
        /// 1~6 分别对应我在线上, Q我吧, 离开, 忙碌, 请勿打扰, 隐身
        /// </summary>
        /// <value>1~6 分别对应我在线上, Q我吧, 离开, 忙碌, 请勿打扰, 隐身</value>
        [DataMember(Name="在线状态", EmitDefaultValue=false)]
        public int? 在线状态 { get; set; }

        /// <summary>
        /// 最大255字节
        /// </summary>
        /// <value>最大255字节</value>
        [DataMember(Name="状态附加信息", EmitDefaultValue=false)]
        public string 状态附加信息 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MpqApiSetOLStatusHttpInput {\n");
            sb.Append("  响应的QQ: ").Append(响应的QQ).Append("\n");
            sb.Append("  在线状态: ").Append(在线状态).Append("\n");
            sb.Append("  状态附加信息: ").Append(状态附加信息).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MpqApiSetOLStatusHttpInput);
        }

        /// <summary>
        /// Returns true if MpqApiSetOLStatusHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of MpqApiSetOLStatusHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MpqApiSetOLStatusHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.响应的QQ == input.响应的QQ ||
                    (this.响应的QQ != null &&
                    this.响应的QQ.Equals(input.响应的QQ))
                ) && 
                (
                    this.在线状态 == input.在线状态 ||
                    (this.在线状态 != null &&
                    this.在线状态.Equals(input.在线状态))
                ) && 
                (
                    this.状态附加信息 == input.状态附加信息 ||
                    (this.状态附加信息 != null &&
                    this.状态附加信息.Equals(input.状态附加信息))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.响应的QQ != null)
                    hashCode = hashCode * 59 + this.响应的QQ.GetHashCode();
                if (this.在线状态 != null)
                    hashCode = hashCode * 59 + this.在线状态.GetHashCode();
                if (this.状态附加信息 != null)
                    hashCode = hashCode * 59 + this.状态附加信息.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
