/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// 取陌生人信息(支持缓存)
    /// </summary>
    [DataContract]
    public partial class CqpCQGetStrangerInfoHttpInput :  IEquatable<CqpCQGetStrangerInfoHttpInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CqpCQGetStrangerInfoHttpInput" /> class.
        /// </summary>
        /// <param name="qqid">目标QQ.</param>
        /// <param name="不使用缓存">不使用缓存.</param>
        public CqpCQGetStrangerInfoHttpInput(long? qqid = default(long?), bool? 不使用缓存 = default(bool?))
        {
            this.Qqid = qqid;
            this.不使用缓存 = 不使用缓存;
        }
        
        /// <summary>
        /// 目标QQ
        /// </summary>
        /// <value>目标QQ</value>
        [DataMember(Name="qqid", EmitDefaultValue=false)]
        public long? Qqid { get; set; }

        /// <summary>
        /// Gets or Sets 不使用缓存
        /// </summary>
        [DataMember(Name="不使用缓存", EmitDefaultValue=false)]
        public bool? 不使用缓存 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CqpCQGetStrangerInfoHttpInput {\n");
            sb.Append("  Qqid: ").Append(Qqid).Append("\n");
            sb.Append("  不使用缓存: ").Append(不使用缓存).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CqpCQGetStrangerInfoHttpInput);
        }

        /// <summary>
        /// Returns true if CqpCQGetStrangerInfoHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of CqpCQGetStrangerInfoHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CqpCQGetStrangerInfoHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Qqid == input.Qqid ||
                    (this.Qqid != null &&
                    this.Qqid.Equals(input.Qqid))
                ) && 
                (
                    this.不使用缓存 == input.不使用缓存 ||
                    (this.不使用缓存 != null &&
                    this.不使用缓存.Equals(input.不使用缓存))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Qqid != null)
                    hashCode = hashCode * 59 + this.Qqid.GetHashCode();
                if (this.不使用缓存 != null)
                    hashCode = hashCode * 59 + this.不使用缓存.GetHashCode();
                return hashCode;
            }
        }

    }

}
