/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// 撤回消息
    /// </summary>
    [DataContract]
    public partial class CqpCQDeleteMsgHttpInput :  IEquatable<CqpCQDeleteMsgHttpInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CqpCQDeleteMsgHttpInput" /> class.
        /// </summary>
        /// <param name="msgId">消息ID.</param>
        public CqpCQDeleteMsgHttpInput(long? msgId = default(long?))
        {
            this.MsgId = msgId;
        }
        
        /// <summary>
        /// 消息ID
        /// </summary>
        /// <value>消息ID</value>
        [DataMember(Name="msgId", EmitDefaultValue=false)]
        public long? MsgId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CqpCQDeleteMsgHttpInput {\n");
            sb.Append("  MsgId: ").Append(MsgId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CqpCQDeleteMsgHttpInput);
        }

        /// <summary>
        /// Returns true if CqpCQDeleteMsgHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of CqpCQDeleteMsgHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CqpCQDeleteMsgHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MsgId == input.MsgId ||
                    (this.MsgId != null &&
                    this.MsgId.Equals(input.MsgId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MsgId != null)
                    hashCode = hashCode * 59 + this.MsgId.GetHashCode();
                return hashCode;
            }
        }

    }

}
