/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// 将群名片加入高速缓存当作.&#x60;
    /// </summary>
    [DataContract]
    public partial class MpqApiCacheNameCardHttpInput :  IEquatable<MpqApiCacheNameCardHttpInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MpqApiCacheNameCardHttpInput" /> class.
        /// </summary>
        /// <param name="群号">群号.</param>
        /// <param name="qq">qq.</param>
        /// <param name="名片">名片.</param>
        public MpqApiCacheNameCardHttpInput(string 群号 = default(string), string qq = default(string), string 名片 = default(string))
        {
            this.群号 = 群号;
            this.Qq = qq;
            this.名片 = 名片;
        }
        
        /// <summary>
        /// Gets or Sets 群号
        /// </summary>
        [DataMember(Name="群号", EmitDefaultValue=false)]
        public string 群号 { get; set; }

        /// <summary>
        /// Gets or Sets Qq
        /// </summary>
        [DataMember(Name="qq", EmitDefaultValue=false)]
        public string Qq { get; set; }

        /// <summary>
        /// Gets or Sets 名片
        /// </summary>
        [DataMember(Name="名片", EmitDefaultValue=false)]
        public string 名片 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MpqApiCacheNameCardHttpInput {\n");
            sb.Append("  群号: ").Append(群号).Append("\n");
            sb.Append("  Qq: ").Append(Qq).Append("\n");
            sb.Append("  名片: ").Append(名片).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MpqApiCacheNameCardHttpInput);
        }

        /// <summary>
        /// Returns true if MpqApiCacheNameCardHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of MpqApiCacheNameCardHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MpqApiCacheNameCardHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.群号 == input.群号 ||
                    (this.群号 != null &&
                    this.群号.Equals(input.群号))
                ) && 
                (
                    this.Qq == input.Qq ||
                    (this.Qq != null &&
                    this.Qq.Equals(input.Qq))
                ) && 
                (
                    this.名片 == input.名片 ||
                    (this.名片 != null &&
                    this.名片.Equals(input.名片))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.群号 != null)
                    hashCode = hashCode * 59 + this.群号.GetHashCode();
                if (this.Qq != null)
                    hashCode = hashCode * 59 + this.Qq.GetHashCode();
                if (this.名片 != null)
                    hashCode = hashCode * 59 + this.名片.GetHashCode();
                return hashCode;
            }
        }

    }

}
