/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// 主动加群.为了避免广告、群发行为。出现验证码时将会直接失败不处理&#x60;
    /// </summary>
    [DataContract]
    public partial class MpqApiJoinGroupHttpInput :  IEquatable<MpqApiJoinGroupHttpInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MpqApiJoinGroupHttpInput" /> class.
        /// </summary>
        /// <param name="响应的QQ">响应的QQ.</param>
        /// <param name="群号">群号.</param>
        /// <param name="附加理由">附加理由.</param>
        public MpqApiJoinGroupHttpInput(string 响应的QQ = default(string), string 群号 = default(string), string 附加理由 = default(string))
        {
            this.响应的QQ = 响应的QQ;
            this.群号 = 群号;
            this.附加理由 = 附加理由;
        }
        
        /// <summary>
        /// Gets or Sets 响应的QQ
        /// </summary>
        [DataMember(Name="响应的QQ", EmitDefaultValue=false)]
        public string 响应的QQ { get; set; }

        /// <summary>
        /// Gets or Sets 群号
        /// </summary>
        [DataMember(Name="群号", EmitDefaultValue=false)]
        public string 群号 { get; set; }

        /// <summary>
        /// Gets or Sets 附加理由
        /// </summary>
        [DataMember(Name="附加理由", EmitDefaultValue=false)]
        public string 附加理由 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MpqApiJoinGroupHttpInput {\n");
            sb.Append("  响应的QQ: ").Append(响应的QQ).Append("\n");
            sb.Append("  群号: ").Append(群号).Append("\n");
            sb.Append("  附加理由: ").Append(附加理由).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MpqApiJoinGroupHttpInput);
        }

        /// <summary>
        /// Returns true if MpqApiJoinGroupHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of MpqApiJoinGroupHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MpqApiJoinGroupHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.响应的QQ == input.响应的QQ ||
                    (this.响应的QQ != null &&
                    this.响应的QQ.Equals(input.响应的QQ))
                ) && 
                (
                    this.群号 == input.群号 ||
                    (this.群号 != null &&
                    this.群号.Equals(input.群号))
                ) && 
                (
                    this.附加理由 == input.附加理由 ||
                    (this.附加理由 != null &&
                    this.附加理由.Equals(input.附加理由))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.响应的QQ != null)
                    hashCode = hashCode * 59 + this.响应的QQ.GetHashCode();
                if (this.群号 != null)
                    hashCode = hashCode * 59 + this.群号.GetHashCode();
                if (this.附加理由 != null)
                    hashCode = hashCode * 59 + this.附加理由.GetHashCode();
                return hashCode;
            }
        }

    }

}
