/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// QQLightApiAddFriendHttpInput
    /// </summary>
    [DataContract]
    public partial class QQLightApiAddFriendHttpInput :  IEquatable<QQLightApiAddFriendHttpInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QQLightApiAddFriendHttpInput" /> class.
        /// </summary>
        /// <param name="目标QQ">目标QQ.</param>
        /// <param name="附加信息">附加信息.</param>
        public QQLightApiAddFriendHttpInput(string 目标QQ = default(string), string 附加信息 = default(string))
        {
            this.目标QQ = 目标QQ;
            this.附加信息 = 附加信息;
        }
        
        /// <summary>
        /// Gets or Sets 目标QQ
        /// </summary>
        [DataMember(Name="目标QQ", EmitDefaultValue=false)]
        public string 目标QQ { get; set; }

        /// <summary>
        /// Gets or Sets 附加信息
        /// </summary>
        [DataMember(Name="附加信息", EmitDefaultValue=false)]
        public string 附加信息 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QQLightApiAddFriendHttpInput {\n");
            sb.Append("  目标QQ: ").Append(目标QQ).Append("\n");
            sb.Append("  附加信息: ").Append(附加信息).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QQLightApiAddFriendHttpInput);
        }

        /// <summary>
        /// Returns true if QQLightApiAddFriendHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of QQLightApiAddFriendHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QQLightApiAddFriendHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.目标QQ == input.目标QQ ||
                    (this.目标QQ != null &&
                    this.目标QQ.Equals(input.目标QQ))
                ) && 
                (
                    this.附加信息 == input.附加信息 ||
                    (this.附加信息 != null &&
                    this.附加信息.Equals(input.附加信息))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.目标QQ != null)
                    hashCode = hashCode * 59 + this.目标QQ.GetHashCode();
                if (this.附加信息 != null)
                    hashCode = hashCode * 59 + this.附加信息.GetHashCode();
                return hashCode;
            }
        }

    }

}
