/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// 机器人发送消息
    /// </summary>
    [DataContract]
    public partial class QQLightApiSendMsgHttpInput :  IEquatable<QQLightApiSendMsgHttpInput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QQLightApiSendMsgHttpInput" /> class.
        /// </summary>
        /// <param name="类型">1.好友消息 2.群消息 3.群临时消息 4.讨论组消息 5.讨论组临时消息 6.QQ临时消息.</param>
        /// <param name="群组">群组.</param>
        /// <param name="qQ号">类型为2，4时可留空.</param>
        /// <param name="内容">内容.</param>
        public QQLightApiSendMsgHttpInput(int? 类型 = default(int?), string 群组 = default(string), string qQ号 = default(string), string 内容 = default(string))
        {
            this.类型 = 类型;
            this.群组 = 群组;
            this.QQ号 = qQ号;
            this.内容 = 内容;
        }
        
        /// <summary>
        /// 1.好友消息 2.群消息 3.群临时消息 4.讨论组消息 5.讨论组临时消息 6.QQ临时消息
        /// </summary>
        /// <value>1.好友消息 2.群消息 3.群临时消息 4.讨论组消息 5.讨论组临时消息 6.QQ临时消息</value>
        [DataMember(Name="类型", EmitDefaultValue=false)]
        public int? 类型 { get; set; }

        /// <summary>
        /// Gets or Sets 群组
        /// </summary>
        [DataMember(Name="群组", EmitDefaultValue=false)]
        public string 群组 { get; set; }

        /// <summary>
        /// 类型为2，4时可留空
        /// </summary>
        /// <value>类型为2，4时可留空</value>
        [DataMember(Name="qQ号", EmitDefaultValue=false)]
        public string QQ号 { get; set; }

        /// <summary>
        /// Gets or Sets 内容
        /// </summary>
        [DataMember(Name="内容", EmitDefaultValue=false)]
        public string 内容 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QQLightApiSendMsgHttpInput {\n");
            sb.Append("  类型: ").Append(类型).Append("\n");
            sb.Append("  群组: ").Append(群组).Append("\n");
            sb.Append("  QQ号: ").Append(QQ号).Append("\n");
            sb.Append("  内容: ").Append(内容).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QQLightApiSendMsgHttpInput);
        }

        /// <summary>
        /// Returns true if QQLightApiSendMsgHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of QQLightApiSendMsgHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QQLightApiSendMsgHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.类型 == input.类型 ||
                    (this.类型 != null &&
                    this.类型.Equals(input.类型))
                ) && 
                (
                    this.群组 == input.群组 ||
                    (this.群组 != null &&
                    this.群组.Equals(input.群组))
                ) && 
                (
                    this.QQ号 == input.QQ号 ||
                    (this.QQ号 != null &&
                    this.QQ号.Equals(input.QQ号))
                ) && 
                (
                    this.内容 == input.内容 ||
                    (this.内容 != null &&
                    this.内容.Equals(input.内容))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.类型 != null)
                    hashCode = hashCode * 59 + this.类型.GetHashCode();
                if (this.群组 != null)
                    hashCode = hashCode * 59 + this.群组.GetHashCode();
                if (this.QQ号 != null)
                    hashCode = hashCode * 59 + this.QQ号.GetHashCode();
                if (this.内容 != null)
                    hashCode = hashCode * 59 + this.内容.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
