/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// QQ群作业发布
    /// </summary>
    [DataContract]
    public partial class CleverQQApiPBHomeWorkHttpInput :  IEquatable<CleverQQApiPBHomeWorkHttpInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CleverQQApiPBHomeWorkHttpInput" /> class.
        /// </summary>
        /// <param name="响应QQ">响应QQ.</param>
        /// <param name="群号">群号.</param>
        /// <param name="作业名">作业名.</param>
        /// <param name="标题">标题.</param>
        /// <param name="内容">内容.</param>
        public CleverQQApiPBHomeWorkHttpInput(string 响应QQ = default(string), string 群号 = default(string), string 作业名 = default(string), string 标题 = default(string), string 内容 = default(string))
        {
            this.响应QQ = 响应QQ;
            this.群号 = 群号;
            this.作业名 = 作业名;
            this.标题 = 标题;
            this.内容 = 内容;
        }
        
        /// <summary>
        /// Gets or Sets 响应QQ
        /// </summary>
        [DataMember(Name="响应QQ", EmitDefaultValue=false)]
        public string 响应QQ { get; set; }

        /// <summary>
        /// Gets or Sets 群号
        /// </summary>
        [DataMember(Name="群号", EmitDefaultValue=false)]
        public string 群号 { get; set; }

        /// <summary>
        /// Gets or Sets 作业名
        /// </summary>
        [DataMember(Name="作业名", EmitDefaultValue=false)]
        public string 作业名 { get; set; }

        /// <summary>
        /// Gets or Sets 标题
        /// </summary>
        [DataMember(Name="标题", EmitDefaultValue=false)]
        public string 标题 { get; set; }

        /// <summary>
        /// Gets or Sets 内容
        /// </summary>
        [DataMember(Name="内容", EmitDefaultValue=false)]
        public string 内容 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CleverQQApiPBHomeWorkHttpInput {\n");
            sb.Append("  响应QQ: ").Append(响应QQ).Append("\n");
            sb.Append("  群号: ").Append(群号).Append("\n");
            sb.Append("  作业名: ").Append(作业名).Append("\n");
            sb.Append("  标题: ").Append(标题).Append("\n");
            sb.Append("  内容: ").Append(内容).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CleverQQApiPBHomeWorkHttpInput);
        }

        /// <summary>
        /// Returns true if CleverQQApiPBHomeWorkHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of CleverQQApiPBHomeWorkHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CleverQQApiPBHomeWorkHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.响应QQ == input.响应QQ ||
                    (this.响应QQ != null &&
                    this.响应QQ.Equals(input.响应QQ))
                ) && 
                (
                    this.群号 == input.群号 ||
                    (this.群号 != null &&
                    this.群号.Equals(input.群号))
                ) && 
                (
                    this.作业名 == input.作业名 ||
                    (this.作业名 != null &&
                    this.作业名.Equals(input.作业名))
                ) && 
                (
                    this.标题 == input.标题 ||
                    (this.标题 != null &&
                    this.标题.Equals(input.标题))
                ) && 
                (
                    this.内容 == input.内容 ||
                    (this.内容 != null &&
                    this.内容.Equals(input.内容))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.响应QQ != null)
                    hashCode = hashCode * 59 + this.响应QQ.GetHashCode();
                if (this.群号 != null)
                    hashCode = hashCode * 59 + this.群号.GetHashCode();
                if (this.作业名 != null)
                    hashCode = hashCode * 59 + this.作业名.GetHashCode();
                if (this.标题 != null)
                    hashCode = hashCode * 59 + this.标题.GetHashCode();
                if (this.内容 != null)
                    hashCode = hashCode * 59 + this.内容.GetHashCode();
                return hashCode;
            }
        }

    }

}
