/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// 邀请对象加入讨论组 成功返回空 失败返回理由
    /// </summary>
    [DataContract]
    public partial class CleverQQApiInviteDisGroupHttpInput :  IEquatable<CleverQQApiInviteDisGroupHttpInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CleverQQApiInviteDisGroupHttpInput" /> class.
        /// </summary>
        /// <param name="响应QQ">机器人QQ.</param>
        /// <param name="讨论组ID">需执行的讨论组ID.</param>
        /// <param name="邀请对象QQ">被邀请对象QQ 多个用  #换行符 分割.</param>
        public CleverQQApiInviteDisGroupHttpInput(string 响应QQ = default(string), string 讨论组ID = default(string), string 邀请对象QQ = default(string))
        {
            this.响应QQ = 响应QQ;
            this.讨论组ID = 讨论组ID;
            this.邀请对象QQ = 邀请对象QQ;
        }
        
        /// <summary>
        /// 机器人QQ
        /// </summary>
        /// <value>机器人QQ</value>
        [DataMember(Name="响应QQ", EmitDefaultValue=false)]
        public string 响应QQ { get; set; }

        /// <summary>
        /// 需执行的讨论组ID
        /// </summary>
        /// <value>需执行的讨论组ID</value>
        [DataMember(Name="讨论组ID", EmitDefaultValue=false)]
        public string 讨论组ID { get; set; }

        /// <summary>
        /// 被邀请对象QQ 多个用  #换行符 分割
        /// </summary>
        /// <value>被邀请对象QQ 多个用  #换行符 分割</value>
        [DataMember(Name="邀请对象QQ", EmitDefaultValue=false)]
        public string 邀请对象QQ { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CleverQQApiInviteDisGroupHttpInput {\n");
            sb.Append("  响应QQ: ").Append(响应QQ).Append("\n");
            sb.Append("  讨论组ID: ").Append(讨论组ID).Append("\n");
            sb.Append("  邀请对象QQ: ").Append(邀请对象QQ).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CleverQQApiInviteDisGroupHttpInput);
        }

        /// <summary>
        /// Returns true if CleverQQApiInviteDisGroupHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of CleverQQApiInviteDisGroupHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CleverQQApiInviteDisGroupHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.响应QQ == input.响应QQ ||
                    (this.响应QQ != null &&
                    this.响应QQ.Equals(input.响应QQ))
                ) && 
                (
                    this.讨论组ID == input.讨论组ID ||
                    (this.讨论组ID != null &&
                    this.讨论组ID.Equals(input.讨论组ID))
                ) && 
                (
                    this.邀请对象QQ == input.邀请对象QQ ||
                    (this.邀请对象QQ != null &&
                    this.邀请对象QQ.Equals(input.邀请对象QQ))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.响应QQ != null)
                    hashCode = hashCode * 59 + this.响应QQ.GetHashCode();
                if (this.讨论组ID != null)
                    hashCode = hashCode * 59 + this.讨论组ID.GetHashCode();
                if (this.邀请对象QQ != null)
                    hashCode = hashCode * 59 + this.邀请对象QQ.GetHashCode();
                return hashCode;
            }
        }

    }

}
