/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// 邀请对象加入群 失败返回错误理由&#x60;
    /// </summary>
    [DataContract]
    public partial class MpqApiGroupInvitationHttpInput :  IEquatable<MpqApiGroupInvitationHttpInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MpqApiGroupInvitationHttpInput" /> class.
        /// </summary>
        /// <param name="响应的QQ">响应的QQ.</param>
        /// <param name="好友QQ">多个好友用换行分割.</param>
        /// <param name="群号">群号.</param>
        public MpqApiGroupInvitationHttpInput(string 响应的QQ = default(string), string 好友QQ = default(string), string 群号 = default(string))
        {
            this.响应的QQ = 响应的QQ;
            this.好友QQ = 好友QQ;
            this.群号 = 群号;
        }
        
        /// <summary>
        /// Gets or Sets 响应的QQ
        /// </summary>
        [DataMember(Name="响应的QQ", EmitDefaultValue=false)]
        public string 响应的QQ { get; set; }

        /// <summary>
        /// 多个好友用换行分割
        /// </summary>
        /// <value>多个好友用换行分割</value>
        [DataMember(Name="好友QQ", EmitDefaultValue=false)]
        public string 好友QQ { get; set; }

        /// <summary>
        /// Gets or Sets 群号
        /// </summary>
        [DataMember(Name="群号", EmitDefaultValue=false)]
        public string 群号 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MpqApiGroupInvitationHttpInput {\n");
            sb.Append("  响应的QQ: ").Append(响应的QQ).Append("\n");
            sb.Append("  好友QQ: ").Append(好友QQ).Append("\n");
            sb.Append("  群号: ").Append(群号).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MpqApiGroupInvitationHttpInput);
        }

        /// <summary>
        /// Returns true if MpqApiGroupInvitationHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of MpqApiGroupInvitationHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MpqApiGroupInvitationHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.响应的QQ == input.响应的QQ ||
                    (this.响应的QQ != null &&
                    this.响应的QQ.Equals(input.响应的QQ))
                ) && 
                (
                    this.好友QQ == input.好友QQ ||
                    (this.好友QQ != null &&
                    this.好友QQ.Equals(input.好友QQ))
                ) && 
                (
                    this.群号 == input.群号 ||
                    (this.群号 != null &&
                    this.群号.Equals(input.群号))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.响应的QQ != null)
                    hashCode = hashCode * 59 + this.响应的QQ.GetHashCode();
                if (this.好友QQ != null)
                    hashCode = hashCode * 59 + this.好友QQ.GetHashCode();
                if (this.群号 != null)
                    hashCode = hashCode * 59 + this.群号.GetHashCode();
                return hashCode;
            }
        }

    }

}
