/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// tean解密算法&#x60;
    /// </summary>
    [DataContract]
    public partial class MpqApiTea解密HttpInput :  IEquatable<MpqApiTea解密HttpInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MpqApiTea解密HttpInput" /> class.
        /// </summary>
        /// <param name="解密内容">解密内容.</param>
        /// <param name="key">key.</param>
        public MpqApiTea解密HttpInput(string 解密内容 = default(string), string key = default(string))
        {
            this.解密内容 = 解密内容;
            this.Key = key;
        }
        
        /// <summary>
        /// Gets or Sets 解密内容
        /// </summary>
        [DataMember(Name="解密内容", EmitDefaultValue=false)]
        public string 解密内容 { get; set; }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [DataMember(Name="key", EmitDefaultValue=false)]
        public string Key { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MpqApiTea解密HttpInput {\n");
            sb.Append("  解密内容: ").Append(解密内容).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MpqApiTea解密HttpInput);
        }

        /// <summary>
        /// Returns true if MpqApiTea解密HttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of MpqApiTea解密HttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MpqApiTea解密HttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.解密内容 == input.解密内容 ||
                    (this.解密内容 != null &&
                    this.解密内容.Equals(input.解密内容))
                ) && 
                (
                    this.Key == input.Key ||
                    (this.Key != null &&
                    this.Key.Equals(input.Key))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.解密内容 != null)
                    hashCode = hashCode * 59 + this.解密内容.GetHashCode();
                if (this.Key != null)
                    hashCode = hashCode * 59 + this.Key.GetHashCode();
                return hashCode;
            }
        }

    }

}
