/* 
 * Newbe.Mahua.HttpApi
 *
 * this is http api document for Newbe.Mahua. You can get some help from http://www.newbe.pro
 *
 * OpenAPI spec version: v1
 * Contact: 472158246@qq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Newbe.Mahua.HttpApiClient.Client.SwaggerDateConverter;

namespace Newbe.Mahua.HttpApiClient.Model
{
    /// <summary>
    /// 置致命错误提示
    /// </summary>
    [DataContract]
    public partial class CqpCQSetFatalHttpInput :  IEquatable<CqpCQSetFatalHttpInput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CqpCQSetFatalHttpInput" /> class.
        /// </summary>
        /// <param name="错误信息">错误信息.</param>
        public CqpCQSetFatalHttpInput(string 错误信息 = default(string))
        {
            this.错误信息 = 错误信息;
        }
        
        /// <summary>
        /// Gets or Sets 错误信息
        /// </summary>
        [DataMember(Name="错误信息", EmitDefaultValue=false)]
        public string 错误信息 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CqpCQSetFatalHttpInput {\n");
            sb.Append("  错误信息: ").Append(错误信息).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CqpCQSetFatalHttpInput);
        }

        /// <summary>
        /// Returns true if CqpCQSetFatalHttpInput instances are equal
        /// </summary>
        /// <param name="input">Instance of CqpCQSetFatalHttpInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CqpCQSetFatalHttpInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.错误信息 == input.错误信息 ||
                    (this.错误信息 != null &&
                    this.错误信息.Equals(input.错误信息))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.错误信息 != null)
                    hashCode = hashCode * 59 + this.错误信息.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
